name: Remove old artifacts

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/Remove old artifacts.yml'
  schedule:
    # Every day at 1am
    - cron: '0 1 * * *'
  watch:
    types: started

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 month'
        # Optional inputs
        # skip-tags: true
        # skip-recent: 5